mod ast;
mod type_error;
mod typechecker;

// Include the parser generated by LALRPOP from grammar/stella.lalrpop.
// The generated module exposes:
//   stella::ProgramParser  – parses a full Stella program
//   stella::ExprParser     – parses a single expression (useful for tests)
//   stella::TypeParser     – parses a single type
lalrpop_util::lalrpop_mod!(pub stella);

fn main() {
    // If a file path is given as the first argument, parse that file.
    // Otherwise fall back to a built-in sample program.
    let src: String = if let Some(path) = std::env::args().nth(1) {
        std::fs::read_to_string(&path).unwrap_or_else(|e| {
            eprintln!("Cannot read {path}: {e}");
            std::process::exit(1);
        })
    } else {
        r#"
language core;

fn main(n : Nat) -> Nat {
  return Nat::rec(n, 0, fn(i : Nat) { return fn(acc : Nat) { return succ(acc) } })
}
"#
        .to_owned()
    };

    let program = match stella::ProgramParser::new().parse(&src) {
        Ok(program) => program,
        Err(e) => {
            eprintln!("Parse error: {e}");
            std::process::exit(1);
        }
    };

    let errors = typechecker::TypeChecker::new().check_program(&program);
    if errors.is_empty() {
        println!("Type OK");
    } else {
        for e in &errors {
            eprintln!("Type error: {e:?}");
        }
        std::process::exit(2);
    }
}

#[cfg(test)]
mod tests {
    include!("../test/parser_tests.rs");
}
