mod ast;

// Include the parser generated by LALRPOP from src/stella.lalrpop.
// The generated module exposes:
//   stella::ProgramParser  – parses a full Stella program
//   stella::ExprParser     – parses a single expression (useful for tests)
//   stella::TypeParser     – parses a single type
lalrpop_util::lalrpop_mod!(pub stella);

fn main() {
    // If a file path is given as the first argument, parse that file.
    // Otherwise fall back to a built-in sample program.
    let src: String = if let Some(path) = std::env::args().nth(1) {
        std::fs::read_to_string(&path)
            .unwrap_or_else(|e| { eprintln!("Cannot read {path}: {e}"); std::process::exit(1); })
    } else {
        r#"
language core;

fn main(n : Nat) -> Nat {
  return Nat::rec(n, 0, fn(i : Nat) { return fn(acc : Nat) { return succ(acc) } })
}
"#.to_owned()
    };

    match stella::ProgramParser::new().parse(&src) {
        Ok(program) => println!("Parsed OK:\n{program:#?}"),
        Err(e)      => { eprintln!("Parse error: {e}"); std::process::exit(1); }
    }
}

#[cfg(test)]
mod tests {
    include!("tests.rs");
}
